### ISSUE TITLE
Error When Using Command `migration:make`, `migrate:run`

### ISSUE THREAD

**Issue by jjjrmy** [sutandojs/sutando#11]
`sutando migrate:make create_flights_table`

```
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at validateString (node:internal/validators:162:11)
    at Module.require (node:internal/modules/cjs/loader:1136:3)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Command.<anonymous> (/Users/admin/.nvm/versions/node/v18.18.0/lib/node_modules/sutando/bin/cli.js:87:20)
    at Command.listener [as _actionHandler] (/Users/admin/.nvm/versions/node/v18.18.0/lib/node_modules/sutando/node_modules/commander/lib/command.js:494:17)
    at /Users/admin/.nvm/versions/node/v18.18.0/lib/node_modules/sutando/node_modules/commander/lib/command.js:1296:65
    at Command._chainOrCall (/Users/admin/.nvm/versions/node/v18.18.0/lib/node_modules/sutando/node_modules/commander/lib/command.js:1193:12)
    at Command._parseCommand (/Users/admin/.nvm/versions/node/v18.18.0/lib/node_modules/sutando/node_modules/commander/lib/command.js:1296:27)
    at /Users/admin/.nvm/versions/node/v18.18.0/lib/node_modules/sutando/node_modules/commander/lib/command.js:1082:27 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v18.18.0
```

**Comment by jjjrmy** [comment]
```js
// /sutando.config.cjs
module.exports = {
  client: 'mysql2',
  connection: {
    host : '127.0.0.1',
    port : 3306,
    user : 'root',
    password : '',
    database : 'myapp'
  },
  migrations: {
    table: 'migrations',
    path: './database/migrations',
  },
  models: {
    path: './models'
  }
};
```

**Comment by jjjrmy** [comment]
closed by #13

**Comment by kiddyuchina** [comment]
Thank you for your pull request!

**Comment by jjjrmy** [comment]
We should look into providing better module support
